apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  selector:
    app: service1
  ports:
    - port: {{ .Values.service1.servicePort }}
      targetPort: {{ .Values.service1.containerPort }}