apiVersion: v1
kind: Service
metadata:
  name: service2-service
spec:
  selector:
    app: service2
  ports:
    - port: {{ .Values.service2.servicePort }}
      targetPort: {{ .Values.service2.containerPort }}